#!/bin/bash

## Description: Enables the EXT:powermail* plugin (Note: Pro EXT:powermail plugins must exist in packages/ext-<powermail-plugin-name>)
## Usage: powermail:disable <powermail-plugin-name>
## Example: ddev powermail:disable powermail_cond



EXT_NAME=$1
LOCAL_EXT_POWERMAIL_PLUGIN_PATH="packages/ext-$EXT_NAME"

RED='\033[0;31m'
NC='\033[0m'

if [[ ! -d "packages/introduction_""$EXT_NAME" ]]; then
  echo "The integration for $EXT_NAME extension does not exists."
  echo "Please provide a pull request for this extension by adding a extension"
  exit 1;
fi


LOCAL_EXT_SOLR_PLUGIN=""
if [[ -d "$LOCAL_EXT_SOLR_PLUGIN_PATH"  ]]; then
  LOCAL_EXT_SOLR_PLUGIN="in2code/$EXT_NAME"
fi

echo "Uninstalling $LOCAL_EXT_SOLR_PLUGIN"
# shellcheck disable=SC2086
if ! ddev composer remove "in2code/introduction-$EXT_NAME" $LOCAL_EXT_POWERMAIL_PLUGIN ; then
  EXECUTED_COMMAND="composer remove \"in2code/introduction-$EXT_NAME\" $LOCAL_EXT_POWERMAIL_PLUGIN"
  echo "Something went wrong by following composer command:"
  echo "    $EXECUTED_COMMAND"
  echo "please check the output from above."
  exit 1;
fi

BELONGING_DOCKER_COMPOSE_SERVICE_FILE="./packages/introduction_$EXT_NAME/docker-compose.$EXT_NAME.yaml"
if [[ -f "$BELONGING_DOCKER_COMPOSE_SERVICE_FILE" ]] && [[ -f ".ddev/docker-compose.$EXT_NAME.yaml" ]]; then
  rm ".ddev/docker-compose.$EXT_NAME.yaml"
  echo -e "\n${RED}The EXT:$EXT_NAME introduced the additional Docker service. The ddev will be restarted to remove the services for EXT:$EXT_NAME.${NC}\n"
  ddev restart
fi
