name: documentation
on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - 'Documentation/**'
jobs:
  documentation:
    runs-on: ubuntu-latest
    name: "Render and deploy documentation"
    steps:
      - name: Get the version
        id: get_version
        run: |
          if [[ ${{ github.ref }} =~ ^refs/tags/[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}$ ]]; then
            echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV;
          else
            echo "version=main" >> $GITHUB_ENV;
          fi
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Render documentation with TYPO3 Docker image"
        run: |
          docker run --rm -v $(pwd):/project \
            ghcr.io/typo3-documentation/render-guides:latest \
            --config=Documentation/
      - name: 'Create release dir, if not exists'
        uses: appleboy/ssh-action@v1
        with:
          host: 31391-3.whserv.de
          username: in2code_website
          key: ${{ secrets.IN2EXTENSIONS_DOCS_DEPLOYMENT }}
          script: |
            mkdir -p /web/www.in2code.de/live/shared/public/extensions/docs/powermail-site/${{ env.version }}
      - name: "Rsync documentation"
        uses: burnett01/rsync-deployments@7.1.0
        with:
          switches: -avzr --delete
          path: Documentation-GENERATED-temp/*
          remote_path: /web/www.in2code.de/live/shared/public/extensions/docs/powermail-site/${{ env.version }}
          remote_host: 31391-3.whserv.de
          remote_user: in2code_website
          remote_key: ${{ secrets.IN2EXTENSIONS_DOCS_DEPLOYMENT }}
